# Generated by Django 2.1.5 on 2019-03-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookSystem', '0003_reader'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reader',
            table='readers',
        ),
    ]
