# Generated by Django 2.1.5 on 2019-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSystem', '0004_auto_20190314_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='country',
            field=models.CharField(default='Bulgaria', max_length=60),
        ),
    ]
