# Generated by Django 2.1.5 on 2019-04-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookSystem', '0005_reader_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
